apiVersion: v1
kind: Service
metadata:
  name: helmfile-learning-prototype-service
spec:
  type: NodePort
  selector:
    app: helmfile-learning-prototype
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001